# Sidebar navigation

- label: 'Introduction'
  link: '/docs/introduction'
#- label: 'Version History'
#  link: '/docs/version-history'
- label: 'Releases'
  link: '/docs/releases'
- label: 'Downloads'
  link: '/download'
#- label: 'Compatibility'
#  link: '/docs/compatibility'
- label: 'Getting started'
  items:
    - label: 'Collector'
      link: '/docs/getting-started/collector'
    - label: 'Java SDK'
      link: '/docs/getting-started/java-sdk'
    - label: 'JavaScript SDK'
      link: '/docs/getting-started/javascript-sdk'
    - label: 'Using AWS X-Ray Tracing'
      link: '/docs/getting-started/java-auto-instrumentation-agent'
    - label: 'Using CloudWatch Metrics'
      link: '/docs/getting-started/cloudwatch-metrics'
- label: Setup
  items:
    - label: 'Permissions'
      link: '/docs/setup/permissions'
    - label: 'Docker Images'
      link: '/docs/setup/docker-images'
    - label: 'For ECS'
      link: '/docs/setup/ecs'
    - label: 'For EC2'
      link: '/docs/setup/ec2'
    - label: 'For EKS'
      link: '/docs/setup/eks'
    - label: 'On-Premises'
      link: '/docs/setup/on-premises'
    - label: 'Build Collector on MS-Windows'
      link: '/docs/setup/build-collector-on-windows'
    - label: 'Build Collector as RPM'
      link: '/docs/setup/build-collector-as-rpm'
    - label: 'Build Collector as Debian'
      link: '/docs/setup/build-collector-as-debian'
- label: Components
  items:
    - label: 'ECS Container Metrics Receiver'
      link: '/docs/components/ecs-metrics-receiver'
    - label: 'X-Ray Receiver'
      link: '/docs/components/x-ray-receiver'
- label: Know Your Data
  items:
    - label: 'Traces'
      link: 'https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md'
    - label: 'Metrics'
      link: 'https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md'
- label: Other
  items:
    - label: 'FAQ'
      link: 'https://aws.amazon.com/otel/faqs/'
    - label: 'Glossary'
      link: 'https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/glossary.md'
    - label: 'Resources'
      link: '/resources'
#- label: Community
#  items:
#    - label: 'Github'
#      link: https://github.com/rocketseat/gatsby-themes
